config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  get :search, controller: :main
  get '/results', to: 'dashboard#index', as: :results

  resources :songs do
    resources :notes, only: [:create, :index, :show]
  end
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :song
#   validates :date, presence: true
#   validates :description, presence: true
#   validates :prac_bpm, presence: true
#   validates :bar_progress, presence: true
#   validates :rating, presence: true, :inclusion => { :in => 1..5 }
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :notes
  # validates :name, presence: true
  # validates :artist, presence: true
  # validates :key, presence: true
  # validates :native_bpm, presence: true
  # validates :time_signature, presence: true
  # validates :photo, presence: true
  # validates :sheet_music, presence: true
  mount_uploader :photo, PhotoUploader
  mount_uploader :sheet_music, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/main_controller.rb
# class MainController < ApplicationController
#   before_action :force_json, only: :search

#   def index; end

#   def search
#       # name_songs = Song.ransack(name_cont: params[:q]).result(distinct: true)
#       # artist_songs = Song.ransack(artist_cont: params[:q]).result(distinct: true)
#       # key_songs = Song.ransack(key_cont: params[:q]).result(distinct: true)
#       # info_songs = Song.ransack(info_cont: params[:q]).result(distinct: true)
#       # bpm_songs = Song.ransack(native_bpm_cont: params[:q]).result(distinct: true)

#       @songs = Song.where("name LIKE ?", "Eric")
#       # @songs = Song.where("name LIKE ? or artist LIKE ? or key LIKE ? or info LIKE ? or native_bpm >= ?",
#       #   "%#{params[:q]}%",
#       #   "%#{params[:q]}%",
#       #   "%#{params[:q]}%",
#       #   "%#{params[:q]}%",
#       #    "#{params[:q]}")
#       # binding.pry
#   end

#   private

#   def force_json
#     request.format = :json
#   end
# end

class MainController < ApplicationController

  before_action :force_json, only: :search

  def index
  end

  def search
        @songs = Song.where("LOWER(name) LIKE ? or LOWER(artist) LIKE ? or LOWER(key) LIKE ? or LOWER(info) LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
  end

  private

  def force_json
    request.format = :json
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @song = Song.find(params[:song_id])
    @note = Note.new(note_params)
    @note.song = @song
    if @note.save
      respond_to do |format|
        format.html { redirect_to song_path(@song) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'songs/show' }
        format.js
      end
    end
  end

  private

  def note_params
    params.require(:note).permit(:description, :bar_progress, :rating, :date, :prac_bpm)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @songs = Song.all.sort_by(&:date_uploaded).reverse
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
    @note = Note.new
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
    @song.date_uploaded = Date.today
    if @song.save
      redirect_to song_path(@song)
    else
      render :new
    end
  end

private

  def song_params
    params.require(:song).permit(:artist, :name, :native_bpm, :info, :photo, :sheet_music, :key, :chords, :date_uploaded, :time_signature)
  end

  # def create_sheet_music
  # sheets = params.dig(:song, :pictures) || []
  #   sheets.each do |sheet|
  #     @song.pictures.create(photo: sheet)
  #   end
  # end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.haml
<div id="results-div"></div>
= javascript_pack_tag 'dashboard'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LetsPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Allura&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div id="root"></div>
    <%= yield %>
     <script>

    </script>

    <script>
      function revealComments() {
      comments = document.querySelectorAll("#hidden")
      comments.forEach((comment) => {
        if (comment.classList.contains("hidden")) {
          return comment.classList.remove("hidden");
        } else {
          return comment.classList.add("hidden")
        }

      })
    };
    </script>

    <script>
      function openNav() {
      if (document.getElementById("mySidenav").style.width === "380px"){
        revealComments();
          return document.getElementById("mySidenav").style.width = "150px";
        } else {
        revealComments();
          return document.getElementById("mySidenav").style.width = "380px"
        }
      };
    </script>

      <script>
         var svgMetro = document.getElementById('metro-svg');
         console.log(svgMetro);


        svgMetro.addEventListener("click",() => {
          console.log("hello")
          const metro = document.getElementById("metro-nome");
            if (metro.classList.contains("hidden")) {
          return metro.classList.remove("hidden");
        } else {
          return metro.classList.add("hidden");
        }
      });

      </script>

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/notes/create.js.erb
<% if @note.persisted? %>
var newNote = '<p id="hidden" class ="show-info-white"><%= @note.date %></p><p id="hidden" class ="show-info"><strong>Practiced at </strong><%= @note.prac_bpm %> <strong>BPM</strong></p><p id="hidden" class ="show-info-key"><%= @note.rating %> <strong>Stars</strong></p><p id="hidden" class ="show-info-key"><strong>Up to Bar</strong> <%= @note.bar_progress %></p><p id="hidden" class ="show-info-key"><strong>How did it go?</strong><br> <%= @note.description %></p><h1 id="hidden" class="show-info-main hidden">__________</h1>'

var allNotes = document.getElementById('notes-side');

console.log(allNotes);
allNotes.insertAdjacentHTML('afterbegin', newNote);

var inputBox = document.getElementById('note_rating')
inputBox.value = "";

var inputBpm = document.getElementById('note_prac_bpm');
inputBpm.value = "";

var inputBar = document.getElementById('note_bar_progress');
inputBar.value = "";

var inputDes = document.getElementById('note_description');
inputDes.value = "";

<% else %>

console.log("Bad Validations")
var inputBox = document.getElementById('note_rating')
inputBox.value = "";

var inputBpm = document.getElementById('note_prac_bpm');
inputBpm.value = "";

var inputBar = document.getElementById('note_bar_progress');
inputBar.value = "";
var inputDes = document.getElementById('note_description');
inputDes.value = "Not Valid, Please fill in all the fields";

<% end %>

// console.log("Bad Validations")
// var inputBox = document.getElementById('note_rating')
// inputBox.value = "";

// var inputBpm = document.getElementById('note_prac_bpm');
// inputBpm.value = "";

// var inputBar = document.getElementById('note_bar_progress');
// inputBar.value = "";
// var inputDes = document.getElementById('note_description');
// inputDes.value = "Not Valid, Please fill in all the fields";

app/views/pages/home.html.erb
<br>
<br>

<!-- <div class="container"> -->

        <div id="main_carousel" class="carousel slide" data-ride="carousel">

          <div class="carousel-inner">

            <div class="carousel-item active">
              <div class="main-box">
              <div class="row main-page">
              <% @songs[0..2].each do |song|  %>
                <div class="col column">
                <%= link_to song_path(song) do %>

                  <div class="each">

                  <h5 class="home-text"><%= song.artist  %></h5>
                  <h6 class="home-text"><%= song.name  %></h6>
                  <%= cl_image_tag song.photo, height: 100, crop: :fill, id: "hover-image" %>
                  <% if !song.notes[0].nil?%>
                    <p id="played-on home-text">Last Played on <%=song.notes[0].date.strftime("%d of %b")%></p>


                  <% else %>
                    <p id="played-on home-text">No logged plays ...</p>
                  <% end %>

                 </p>
                 </div>
                <% end %>
              </div>
              <% end  %>
             </div>
          </div>
          </div>

            <div class="carousel-item">
            <div class="main-box">

             <div class="row main-page-second">
              <% @songs[3..5].each do |song|  %>
                <div class="col column">


                 <%= link_to song_path(song) do %>
                  <div class="each">

                  <h5 class="home-text"><%= song.artist  %></h5>
                  <h6 class="home-text"><%= song.name  %></h6>
                  <%= cl_image_tag song.photo, height: 100, crop: :fill, id: "hover-image" %>

                  <% if !song.notes[0].nil?%>
                    <p id="played-on home-text">Played on <%=song.notes[0].date.strftime("%d of %b")%></p>
                  <% else %>
                    <p id="played-on home-text">No logged plays ...</p>
                  <% end %>

                  </div>
                <% end %>
                </div>

              <% end  %>

            </div>
            </div>

          </div>
          <a class="carousel-control-prev" href="#main_carousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#main_carousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>


<!-- </div> -->
</div>
<br>
<br>
<br>
<div class="main-picture">
  <br>
  <br>

  <h1 class="footer-text">Track your musical progress one practice at a time!</h1>

</div>

app/views/shared/_navbar.hmtl.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="nav-link">
    <%= link_to results_path, class: "navbar-brand" do %>
      <h2 class="rotate browse-black">Bro</h2>
      <h2 class="rotate browse browse-white">___wse</h2>
    <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div>

    <%= link_to root_path, class: "navbar-brand" do %>
      <h1 id="nav-main-header">Let's Practice</h1>
    <% end %>
<img id="metro-svg" class="" src="https://res.cloudinary.com/dpxibu6l4/image/upload/v1573938065/metronome_atajwh.svg" alt="">
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <div class="nav-link">
          <%= link_to new_song_path, class: "nav-link" do %>
            <h2 class="upload">Upload</h2>
          <% end %>
        </div>
      </li>
      <li class="nav-item active">
        <div class="nav-link">
          <div id="metro"></div>
            <!-- <h5 class="metronome">88bpm</h5> -->
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="nav-link">
    <%= link_to results_path, class: "navbar-brand" do %>
      <h2 class="rotate browse-black">Bro</h2>
      <h2 class="rotate browse browse-white">___wse</h2>
    <% end %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div>

    <%= link_to root_path, class: "navbar-brand" do %>
      <h1 id="nav-main-header">Let's Practice</h1>
    <% end %>
<img id="metro-svg" class="" src="https://res.cloudinary.com/dpxibu6l4/image/upload/v1573938065/metronome_atajwh.svg" alt="">
  </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <div class="nav-link">
          <%= link_to new_song_path, class: "nav-link" do %>
            <h2 class="upload">Upload</h2>
          <% end %>
        </div>
      </li>
      <li class="nav-item active">
        <div class="nav-link">
          <div id="metro"></div>
            <%= javascript_pack_tag 'metronome' %>
          <!-- = javascript_pack_tag 'metronome' -->
            <!-- <h5 class="metronome">88bpm</h5> -->
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_side_nav.html.erb
<div id="mySidenav" class="sidenav">
  <br>
  <br>

  <div id="notes-toggle" class ="show-info-comments" style="cursor:pointer font-size: 30px" onclick="openNav()">
    <h6 class="comment-button-animation">Notes</h6>
  </div>
  <div class="container">
    <div class="container form-note">
    <%= simple_form_for([ @song, @note ], remote: true, html: { class: "hidden", id:"hidden"}) do |form| %>
    <h5 id="hidden" class ="show-info-white hidden">Add New Practice Note</h5>
    <%= form.input :date, as: :date %>
    <%= form.input :prac_bpm, :label => "BPM", as: :numeric %>
    <%= form.input :bar_progress, :label => "Upto Bar", as: :numeric %>
    <%= form.input :rating, :label => "Rating", as: :numeric %>
    <%= form.input :description, :label => "How did your practice go?", as: :text %>
    <%= form.submit "Add Note", :class => "btn-dark" %>
    <% end %>
    </div>
    <h1 id="hidden" class="show-info-main hidden">__________</h1>

    <!-- <h5 id="hidden" class ="show-info-white hidden">Notes</h5> -->

    <div id="reviews">
    <% if @song.notes.blank? %>
      <div id="notes-side">
      </div>
      <p id="hidden" class ="show-info hidden">You have no saved notes for your practice of <%= @song.name %>. <u>Why not add one and we can get started tracking your progress. </u></p>
    <% else %>
    <h5 id="hidden" class ="show-info hidden">Practice Log</h5>
      <% @song.notes.reverse.each do |note| %>
      <div id="notes-side">
      <p id="hidden" class ="show-info-white hidden"><%= note.date %></p>
      <p id="hidden" class ="show-info hidden"><strong>Practiced at </strong><%= note.prac_bpm %> <strong>BPM</strong></p>
      <p id="hidden" class ="show-info-key hidden"><%= note.rating %> <strong>Stars</strong></p>
      <p id="hidden" class ="show-info-key hidden"><strong>Up to Bar</strong> <%= note.bar_progress %></p>
      <p id="hidden" class ="show-info-key hidden"><strong>How did it go?</strong>
      <br> <%= note.description %></p>

      <h1 id="hidden" class="show-info-main hidden">__________</h1>
      </div>
      <% end %>
    <% end %>
    </div>



<!--   <p id="hidden" class ="show-info-key hidden">Note info goes here</p> -->
 <!--  <p id="hidden" class ="show-info-key hidden">Bpm info</p> -->
  <!-- <p id="hidden" class ="show-info-key hidden">Rating info</p> -->
  </div>
</div>

app/views/songs/index.html.erb
<div class="row show-page">
</div>

<div id="search-results" class="container">

  <% @songs.each do |song| %>
    <%= link_to song_path(song) do %>
      <div class="card-product index-card">
        <%= cl_image_tag song.photo, height: 200, crop: :fill, id: "hover-image" %>

        <div class="card-product-infos">
          <h2><%= song.artist%></h2>
          <h3><%= song.name%></h3>
          <h3 id="bpm-key-card"><%= song.native_bpm%> BPM  /  <%= song.key %> </h3>
        </div>
      </div>
    <% end %>
  <% end %>
</div>



<div class="container">

    <div class="index-card row">
      <div class="">

      </div>
      <div class="">
      </div>
    </div>

  </div>

app/views/songs/new.html.erb
<div class="container">
  <%= simple_form_for @song do |f| %>
    <div class="row new-form" style="padding-top: 50px;">
      <div class="col-xs-12 col-lg-12 ">
      <%= f.input :artist, label: "Artist Name "%>
      <%= f.input :name, label: "Song Name "  %>
      <%= f.input :time_signature, label: "Time Signature " %>
      <%= f.input :native_bpm, label: "Native BPM " %>
      <%= f.input :key, label: "Key " %>
      <%= f.input :chords, label: "Chords " %>

      <%= f.input :info, label: "Description " %>
      </div>

      <div class="col-xs-12 col-lg-8">

      <%= f.input :photo, label: "Album Art "%>
      <%= f.input :sheet_music, label: "Sheet Music " %>
      <%= f.input :photo_cache, as: :hidden %>

      <%= f.submit %>
      </div>

    </div>
  <% end %>
</div>

app/views/songs/show.html.erb
  <%= render 'shared/side_nav' %>

  <div class="row show-page">
    <div class="col-1"></div>
    <div class="col-2 show-col-left">
      <%= cl_image_tag @song.photo, height: 120, crop: :fill %>

      <br>
      <br>
      <br>
      <br>
      <h4 class="show-info-main"><%= @song.artist %></h4>

      <h5 class="show-info"><%= @song.name %></h5>

      <h5 class="show-info-white"><%= @song.native_bpm %> BPM</h5>
      <h5 class="show-info-time">in <%= @song.time_signature %></h5>
      <h6 class="show-info-key"><%= @song.key%></h6>
      <h3>______</h3>
      <p><%= @song.info %></p>
      <h3>______</h3>
      <h5 class="show-info-key"><%= @song.chords %></h5>
    </div>

    <div class="col-8 show-col-center">
      <%= cl_image_tag @song.sheet_music, height: 1000, crop: :fill %>
    </div>

    <div class="col-1">
      <br>


    </div>

    <div class=""></div>


  </div>